name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Build
        run: go build -v ./...

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: speedMeter
          path: ./speedMeter

#  upx:
#    runs-on: ubuntu-16.04
#    needs: build
#    steps:
#    - name: Download a Build Artifact
#      uses: actions/download-artifact@v2.0.8
#      with:
#        name: speedMeter
#        path: ./
#
#    - name: upx
#      run: chmod 755 ./upx_compress.sh && ./upx_compress.sh
#
#    - name: ls
#      run: ls -al
#
#    - name: Upload a Build Artifact
#      uses: actions/upload-artifact@v2.2.2
#      with:
#        name: speedMeterUPXed
#        path: ./speedMeter